adminUser:
  password: vault:falconazure/adminUser:password
  username: admin
dashboardUrl: https://dashboard.play-jxaas.live
enableDocker: false
pipelineUser:
  email: arcalos-admin@googlegroups.com
  token: vault:falconazure/pipelineUser:token
  username: cloudbees-ci-cd-play[bot]
prow:
  hmacToken: vault:falconazure/prow:hmacToken
segmentWriteKey: vault:falconazure:segmentWriteKey
